### ISSUE TITLE
Can remove commented out code

### ISSUE THREAD

**Issue by Jbarget** [FACN1/Week3-ShecureShel#36]
Its good practice to remove code that is commented out before committing.
On a big project its easy to forget about them and then they end up just staying there

**Comment by Jbarget** [comment]
https://github.com/FACN1/Week3-ShecureShel/blob/master/javascript/input.js#L24

**Comment by Jbarget** [comment]
https://github.com/FACN1/Week3-ShecureShel/blob/master/style/style.css#L1-L5

**Comment by Suuuuha** [comment]
Done,thx !

**Comment by Jbarget** [comment]
perfect!
