### ISSUE TITLE
Does not work in incognito mode

### ISSUE THREAD

**Issue by HilbertSpitzer** [FACN1/Week3-ShecureShel#37]
The search does not work in incognito mode
And yes, I have the "allow-control-allow-origin" extension
If that's how its just supposed to be then please put a footnote or something. But at the very least I didn't experience any problems with other search engines in incognito mode so please don't grab a rope if you think my complaint is invalid and try to explain what's going on here

**Comment by macintoshhelper** [comment]
Extensions are disabled in incognito, for security purposes - this is a browser side issue.

**Comment by HilbertSpitzer** [comment]
Really? all extensions? Pop-up blockers too? This is news to me, I even used many search extensions with no problem in incognito mode
